sudo: required
services:
    - docker

before_install:
    - docker build -t lucheya/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true lucheya/react-test npm test

after_success:
    - docker build -t lucheya/multi-client ./client
    - docker build -t lucheya/multi-server ./server
    - docker build -t lucheya/multi-worker ./worker
    - docker build -t lucheya/multi-nginx ./nginx

    # Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take these images and push them to Docker Hub
    - docker push lucheya/multi-server
    - docker push lucheya/multi-worker
    - docker push lucheya/multi-nginx
    - docker push lucheya/multi-client

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-985886119194
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY